FROM ubuntu:focal

ENV TZ=Asia/Ho_Chi_Minh
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt update --fix-missing && \
    apt upgrade && \
    apt install -y git vim
RUN git clone https://github.com/nVietUK/nVietUK.git
RUN cd nVietUK/ && \
    chmod +x .sh/install-tensorflow.sh && \
    chmod +x .sh/install-tensorRT.sh && \
    chmod +x .sh/install-python.sh
RUN cd nVietUK/ && .sh/install-python.sh && ls
RUN cd nVietUK/ && .sh/install-tensorRT.sh --docker 
RUN cd nVietUK/ && .sh/install-tensorflow.sh --docker