name: Khai triển Github Page

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  Deploy:
    name: "Khai triển trang Github"
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate WEBP files
        run: |
          cd ./.jpg/
          for file in ./*; do cwebp -q 50 "$file" -o "../.webp/${file%.*}.webp"; done

      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Remove Unnecessary
        run: |
          rm "Góc học tập" -fr
          rm ./.jpg/ -fr
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "."
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
