name: Deploy Paper Minecraft server
on:
  workflow_dispatch:
jobs:
  my_job:
    name: start minecraft server
    runs-on: ubuntu-18.04
    env:
      NGROK_TOKEN : ${{ secrets.NGROK_TOKEN }}
    steps:
      - name: 'Set up latest Oracle JDK 17'
        uses: oracle-actions/setup-java@v1
        with:
          website: oracle.com
          release: 17
      - name: 'Downloading PaperMC'
        uses: just-dev-creator/install-paper@v1.0.3
        with:
          path: './paperclip.jar'
      - name: 'Accepting EULA'
        run: echo "eula=true" > eula.txt
        
      - name: ngrok-tunnel
        uses: vmactions/ngrok-tunnel@v0.0.1
        with:
          protocol: tcp
          port: 25565
        
      - name: 'Deploy server'
        run: nohup java -jar ./paperclip.jar &
